import { saltAndHashPassword } from "@/lib/password"
import prisma from "@/lib/prisma"

async function main() {
    const admin = await prisma.user.create({
        data: {
            email: 'admin@hospital.com',
            pswdHash: saltAndHashPassword('admin123'),
        }
    })
    console.log(`Admin user created: ${admin.email}`)

    await prisma.patient.createMany({
        data: [
            {
                name: "Alice Johnson",
                age: 30,
                gender: "Female",
                contact: "123-456-7890",
                email: "alice@example.com",
                address: "123 Main St",
                city: "New York",
                state: "NY",
                zipCode: "10001",
                insurance: "Blue Cross",
                status: "Active",
                lastVisit: new Date("2024-03-15"),
                doctor: "Dr. Smith",
                notes: "Regular check-up",
            },
            {
                name: "Bob Williams",
                age: 45,
                gender: "Male",
                contact: "987-654-3210",
                email: "bob@example.com",
                address: "456 Elm St",
                city: "Los Angeles",
                state: "CA",
                zipCode: "90001",
                insurance: "Medicare",
                status: "Inactive",
                lastVisit: new Date("2023-11-20"),
                doctor: "Dr. Johnson",
                notes: "Diabetes management",
            },
            {
                name: "Charlie Davis",
                age: 50,
                gender: "Male",
                contact: "555-123-4567",
                email: "charlie@example.com",
                address: "789 Oak St",
                city: "Chicago",
                state: "IL",
                zipCode: "60601",
                insurance: "Aetna",
                status: "Active",
                lastVisit: new Date("2024-02-10"),
                doctor: "Dr. Brown",
                notes: "Blood pressure check",
            },
            {
                name: "Diana Evans",
                age: 29,
                gender: "Female",
                contact: "222-333-4444",
                email: "diana@example.com",
                address: "321 Birch St",
                city: "Houston",
                state: "TX",
                zipCode: "77001",
                insurance: "Cigna",
                status: "Active",
                lastVisit: new Date("2024-03-01"),
                doctor: "Dr. White",
                notes: "Annual physical",
            },
            {
                name: "Edward Harris",
                age: 55,
                gender: "Male",
                contact: "999-888-7777",
                email: "edward@example.com",
                address: "654 Pine St",
                city: "Phoenix",
                state: "AZ",
                zipCode: "85001",
                insurance: "UnitedHealth",
                status: "Inactive",
                lastVisit: new Date("2023-09-05"),
                doctor: "Dr. Green",
                notes: "Cholesterol check",
            },
            {
                name: "Fiona Carter",
                age: 33,
                gender: "Female",
                contact: "777-666-5555",
                email: "fiona@example.com",
                address: "987 Maple St",
                city: "Philadelphia",
                state: "PA",
                zipCode: "19101",
                insurance: "Humana",
                status: "Active",
                lastVisit: new Date("2024-01-20"),
                doctor: "Dr. Adams",
                notes: "Pregnancy consultation",
            },
            {
                name: "George Thompson",
                age: 40,
                gender: "Male",
                contact: "333-222-1111",
                email: "george@example.com",
                address: "159 Cedar St",
                city: "San Antonio",
                state: "TX",
                zipCode: "78201",
                insurance: "Medicaid",
                status: "Inactive",
                lastVisit: new Date("2023-07-12"),
                doctor: "Dr. Carter",
                notes: "Back pain treatment",
            },
            {
                name: "Hannah Wilson",
                age: 28,
                gender: "Female",
                contact: "444-555-6666",
                email: "hannah@example.com",
                address: "753 Walnut St",
                city: "San Diego",
                state: "CA",
                zipCode: "92101",
                insurance: "Blue Shield",
                status: "Active",
                lastVisit: new Date("2024-02-25"),
                doctor: "Dr. Garcia",
                notes: "Skin allergy treatment",
            },
            {
                name: "Ian Martinez",
                age: 47,
                gender: "Male",
                contact: "111-222-3333",
                email: "ian@example.com",
                address: "852 Spruce St",
                city: "Dallas",
                state: "TX",
                zipCode: "75201",
                insurance: "Kaiser Permanente",
                status: "Inactive",
                lastVisit: new Date("2023-10-30"),
                doctor: "Dr. Wilson",
                notes: "Heart condition monitoring",
            },
            {
                name: "Jessica Lopez",
                age: 35,
                gender: "Female",
                contact: "666-777-8888",
                email: "jessica@example.com",
                address: "951 Cherry St",
                city: "San Jose",
                state: "CA",
                zipCode: "95101",
                insurance: "Tricare",
                status: "Active",
                lastVisit: new Date("2024-03-05"),
                doctor: "Dr. Martinez",
                notes: "Migraine treatment",
            },
        ],
    });

    await prisma.staff.createMany({
        data: [
            {
                id: "1",
                name: "Dr. Alice Johnson",
                role: "Doctor",
                department: "Cardiology",
                status: "Active",
                contact: "123-456-7890",
                email: "alice.johnson@example.com",
                joined: new Date("2020-05-10"),
                gender: "Female",
                address: "123 Heart Ave, NY",
                qualifications: "MD, Cardiology",
                specialization: "Heart Surgery",
                experience: "10 years",
                notes: "Specialist in heart transplants",
            },
            {
                id: "2",
                name: "Dr. Michael Smith",
                role: "Doctor",
                department: "Neurology",
                status: "Active",
                contact: "987-654-3210",
                email: "michael.smith@example.com",
                joined: new Date("2018-03-22"),
                gender: "Male",
                address: "456 Brain St, CA",
                qualifications: "MD, Neurology",
                specialization: "Brain Disorders",
                experience: "8 years",
                notes: "Researcher in neurodegenerative diseases",
            },
            {
                id: "3",
                name: "Nurse Jessica Brown",
                role: "Nurse",
                department: "Pediatrics",
                status: "Active",
                contact: "555-123-4567",
                email: "jessica.brown@example.com",
                joined: new Date("2019-08-15"),
                gender: "Female",
                address: "789 Kids Ln, TX",
                qualifications: "RN",
                specialization: "Child Care",
                experience: "5 years",
                notes: "Works well with children",
            },
            {
                id: "4",
                name: "Dr. Robert White",
                role: "Doctor",
                department: "Orthopedics",
                status: "Active",
                contact: "444-987-6543",
                email: "robert.white@example.com",
                joined: new Date("2015-02-10"),
                gender: "Male",
                address: "321 Bone Rd, FL",
                qualifications: "MD, Orthopedics",
                specialization: "Joint Replacement",
                experience: "12 years",
                notes: "Expert in knee and hip replacements",
            },
            {
                id: "5",
                name: "Nurse Emily Davis",
                role: "Nurse",
                department: "Emergency",
                status: "Active",
                contact: "666-234-7890",
                email: "emily.davis@example.com",
                joined: new Date("2021-06-05"),
                gender: "Female",
                address: "555 ER Blvd, OH",
                qualifications: "RN",
                specialization: "Emergency Care",
                experience: "3 years",
                notes: "Handles trauma cases efficiently",
            },
            {
                id: "6",
                name: "Dr. William Harris",
                role: "Doctor",
                department: "General Medicine",
                status: "Active",
                contact: "777-345-6789",
                email: "william.harris@example.com",
                joined: new Date("2017-11-12"),
                gender: "Male",
                address: "101 Clinic St, WA",
                qualifications: "MD",
                specialization: "General Practitioner",
                experience: "6 years",
                notes: "Family doctor with a broad knowledge base",
            },
            {
                id: "7",
                name: "Dr. Olivia Martinez",
                role: "Doctor",
                department: "Dermatology",
                status: "Active",
                contact: "888-456-7890",
                email: "olivia.martinez@example.com",
                joined: new Date("2016-09-08"),
                gender: "Female",
                address: "222 Skin Care Rd, AZ",
                qualifications: "MD, Dermatology",
                specialization: "Skin Treatments",
                experience: "7 years",
                notes: "Specializes in acne and skin cancer treatments",
            },
            {
                id: "8",
                name: "Nurse Daniel Lee",
                role: "Nurse",
                department: "ICU",
                status: "Active",
                contact: "999-567-8901",
                email: "daniel.lee@example.com",
                joined: new Date("2014-12-20"),
                gender: "Male",
                address: "333 Critical Ln, CO",
                qualifications: "RN",
                specialization: "Intensive Care",
                experience: "9 years",
                notes: "Works in critical care and ICU",
            },
            {
                id: "9",
                name: "Dr. Sophia Wilson",
                role: "Doctor",
                department: "Ophthalmology",
                status: "Active",
                contact: "101-678-9012",
                email: "sophia.wilson@example.com",
                joined: new Date("2022-04-30"),
                gender: "Female",
                address: "444 Vision St, NV",
                qualifications: "MD, Ophthalmology",
                specialization: "Eye Surgery",
                experience: "2 years",
                notes: "Performs laser eye surgeries",
            },
            {
                id: "10",
                name: "Nurse James Brown",
                role: "Nurse",
                department: "Surgery",
                status: "Active",
                contact: "202-789-0123",
                email: "james.brown@example.com",
                joined: new Date("2013-07-15"),
                gender: "Male",
                address: "555 OR Blvd, MA",
                qualifications: "RN",
                specialization: "Surgical Nursing",
                experience: "11 years",
                notes: "Assists in complex surgeries",
            },
        ],
    });

    console.log("✅ 10 staff members created successfully.");

    const patients = await prisma.patient.findMany();
    const doctors = await prisma.staff.findMany();

    await prisma.appointment.createMany({
        data: [
            {
                patientId: patients[0].id,
                doctorId: doctors[0].id,
                department: "Cardiology",
                date: new Date("2025-04-01"),
                time: "10:00 AM",
                status: "Scheduled",
                type: "Consultation",
                duration: "30 minutes",
                notes: "Routine heart check-up",
            },
            {
                patientId: patients[1].id,
                doctorId: doctors[1].id,
                department: "Neurology",
                date: new Date("2025-04-02"),
                time: "11:30 AM",
                status: "Completed",
                type: "Follow-up",
                duration: "20 minutes",
                notes: "Post MRI consultation",
            },
            {
                patientId: patients[2].id,
                doctorId: doctors[2].id,
                department: "Orthopedics",
                date: new Date("2025-04-03"),
                time: "9:00 AM",
                status: "Scheduled",
                type: "Surgery",
                duration: "2 hours",
                notes: "Knee replacement surgery",
            },
            {
                patientId: patients[3].id,
                doctorId: doctors[0].id,
                department: "Cardiology",
                date: new Date("2025-04-04"),
                time: "2:00 PM",
                status: "Canceled",
                type: "Check-up",
                duration: "15 minutes",
                notes: "Patient rescheduled",
            },
            {
                patientId: patients[4].id,
                doctorId: doctors[3].id,
                department: "Dermatology",
                date: new Date("2025-04-05"),
                time: "1:00 PM",
                status: "Scheduled",
                type: "Consultation",
                duration: "30 minutes",
                notes: "Acne treatment consultation",
            },
            {
                patientId: patients[5].id,
                doctorId: doctors[1].id,
                department: "Neurology",
                date: new Date("2025-04-06"),
                time: "10:30 AM",
                status: "Scheduled",
                type: "MRI Review",
                duration: "45 minutes",
                notes: "Discuss MRI results",
            },
            {
                patientId: patients[6].id,
                doctorId: doctors[2].id,
                department: "General Medicine",
                date: new Date("2025-04-07"),
                time: "4:00 PM",
                status: "Completed",
                type: "Routine Check-up",
                duration: "20 minutes",
                notes: "Annual health check-up",
            },
            {
                patientId: patients[7].id,
                doctorId: doctors[4].id,
                department: "Ophthalmology",
                date: new Date("2025-04-08"),
                time: "3:00 PM",
                status: "Scheduled",
                type: "Eye Exam",
                duration: "30 minutes",
                notes: "Check for vision correction",
            },
            {
                patientId: patients[8].id,
                doctorId: doctors[0].id,
                department: "Cardiology",
                date: new Date("2025-04-09"),
                time: "9:30 AM",
                status: "Completed",
                type: "ECG Test",
                duration: "40 minutes",
                notes: "Evaluate heart function",
            },
            {
                patientId: patients[9].id,
                doctorId: doctors[3].id,
                department: "Dermatology",
                date: new Date("2025-04-10"),
                time: "5:00 PM",
                status: "Scheduled",
                type: "Skin Biopsy",
                duration: "1 hour",
                notes: "Check for skin conditions",
            },
        ],
    });

    console.log("✅ 10 appointments created successfully.");

    const roomData = patients.map((patient, index) => ({
        name: (101 + index).toString(), // Room names: "101", "102", ..., "110"
        type: index % 3 === 0 ? "ICU" : index % 3 === 1 ? "General Ward" : "Private Room",
        floor: index < 5 ? "1" : "2", // First 5 rooms on floor 1, others on floor 2
        beds: index % 2 === 0 ? 1 : 2, // Alternate between 1 and 2 beds
        status: "Occupied",
        patientId: patient.id,
        equipment: index % 3 === 0 ? "Ventilator, ECG Monitor" : "Oxygen Cylinder",
        notes: `Room ${101 + index} assigned to ${patient.name}`,
    }));

    await prisma.room.createMany({
        data: roomData,
    });

    console.log("✅ 10 rooms created successfully.");
}
main()
    .then(async () => {
        await prisma.$disconnect()
    })
    .catch(async (e) => {
        console.error(e)
        await prisma.$disconnect()
        process.exit(1)
    })